#!/bin/sh

BIN_DIR=$(dirname "$0")
if [ "$BIN_DIR" = "." ]
then
	BIN_DIR=$(pwd)
fi

PROJECTS_CONF="$BIN_DIR/projects.conf"
BASE_URL_CONF="$BIN_DIR/base-url.conf"
GIT_DIR=$(dirname "$BIN_DIR")

read BASE_URL < "$BASE_URL_CONF"

IFS=,

while read PROJECT BUILD_CMD INSTALL_CMD
do
	if [ -d "$GIT_DIR/$PROJECT" ]
	then
		cd "$GIT_DIR/$PROJECT"
		git pull origin master
	else
		cd "$GIT_DIR"
		git clone "$BASE_URL/$PROJECT".git
		cd "$PROJECT"
	fi
	$BUILD_CMD
	$INSTALL_CMD
done < "$PROJECTS_CONF"

