#!/bin/sh

BIN_DIR=$(dirname "$0")
if [ "$BIN_DIR" = "." ]
then
	BIN_DIR=$(pwd)
fi

PROJECTS_CONF="$BIN_DIR/projects.conf"
BASE_URL_CONF="$BIN_DIR/base-url.conf"
GIT_DIR=$(dirname "$BIN_DIR")

read BASE_URL < "$BASE_URL_CONF"

OS=$(uname -o)
IFS=,

cat "$PROJECTS_CONF" | tr -d '\r' | while read PROJECT
do
	if [ -d "$GIT_DIR/$PROJECT" ]
	then
		cd "$GIT_DIR/$PROJECT"
		git pull origin master
	else
		cd "$GIT_DIR"
		git clone "$BASE_URL/$PROJECT".git
		cd "$PROJECT"
	fi

	if [ -f Makefile.$OS ]
	then
		make -f Makefile.$OS install
	elif [ -f Makefile ]
	then
		make install
	elif [ -f build.xml ]
	then
		ant install
	elif [ -f build.gradle ]
	then
		gradle build install
	fi
done

